{
 "title": "register : request/response",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "msgs : request/response",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/msgs/{username}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_response_size_bytes_count{handler=\"/msgs/{username}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fllws : request/response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/fllws/{username}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_response_size_bytes_count{handler=\"/fllws/{username}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "register : request/response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/register\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_response_size_bytes_count{handler=\"/register\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prometheus : connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "prometheus_ready", "legendFormat": "__auto" }
   ]
  }
 ]
}