# Generated by Django 4.1.5 on 2023-03-14 20:46
import datetime
from django.utils import timezone
from django.conf import settings
from django.db import connections, migrations, models
import django.utils.timezone
from django.contrib.auth import get_user_model

def copy_messages(apps, schema_editor):
    # Get a connection to the old database
    old_db = connections['old_db']

    # Execute a SELECT statement to retrieve the data from the old table
    with old_db.cursor() as cursor:
        cursor.execute("SELECT * FROM message")

        # Iterate over the rows and insert them into the new table
        for row in cursor.fetchall():
            
            
            newMessage = apps.get_model('MiniTwit', 'message')
            new_message = newMessage()
            author = apps.get_model('MiniTwit', 'User').objects.get(id=row[1])
            new_message.author = author
            new_message.text = row[2]
            pub_date = datetime.datetime.fromtimestamp(row[3])
            pub_date = timezone.make_aware(pub_date, timezone.get_default_timezone())
            new_message.pub_date = pub_date
            new_message.flagged = row[4]

            new_message.save()

def copy_followers(apps, schema_editor):
    # Get a connection to the old database
    old_db = connections['old_db']

    # Execute a SELECT statement to retrieve the data from the old table
    with old_db.cursor() as cursor:
        cursor.execute("SELECT * FROM follower")

        # Iterate over the rows and insert them into the new table
        for row in cursor.fetchall():

            newFollower = apps.get_model('MiniTwit', 'follower')
            new_follower = newFollower()
        
            new_follower.who = apps.get_model('MiniTwit', 'User').objects.get(id=row[0])
            new_follower.whom = apps.get_model('MiniTwit', 'User').objects.get(id=row[1])

            new_follower.save()


class Migration(migrations.Migration):

    dependencies = [
        ('MiniTwit', '0001_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('pub_date', models.DateTimeField(null=False)),
                ('flagged', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who', to=settings.AUTH_USER_MODEL)),
                ('whom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follower',
            },
        ),
        migrations.RunPython(copy_messages),
        migrations.RunPython(copy_followers),
    ]
